[build]
target = "avr-none"
rustflags = ["-C", "target-cpu=attiny1604"]

[target.'cfg(target_arch = "avr")']
runner = "avrdude -p t1604 -c serialupdi -P COM34 -e -U "

[unstable]
build-std = ["core"]
