[build]
target = "avr-none"
rustflags = ["-C", "target-cpu=attiny1604"]

[target.'cfg(target_arch = "avr")']
runner = "avrdude -v -p t1604 -cavr109 -P COM23 -Uflash:w:target/avr-attiny1604/debug/NONIK0.elf:e"

[unstable]
build-std = ["core"]
