[build]
#target = "avr-none"
target = "avr-specs/avr-attiny1604.json"
rustflags = ["-C", "target-cpu=attiny1604"]

[target.'cfg(target_arch = "avr")']
runner = "avrdude -p t1604 -c serialupdi -P COM3 -e -U "

[unstable]
build-std = ["core"]
